services:
  nginx:
    image: ci-nginx
    build:
      context: ../nginx
      dockerfile: Dockerfile.ci
    volumes: []
    ports:
      - "0:80"
  kafka:
    ports: []
  zookeeper:
    ports: []
  mock-server:
    ports:
      - "0:1080"
  selenium-hub:
    ports:
      - "0:4444"
  centrifugo:
    ports: []

networks:
  default:
