services:
  nginx:
    image: ci-nginx
    build:
      context: ../nginx
      dockerfile: Dockerfile.ci
    volumes: []
    ports:
      - "0:80"
  kafka:
    ports:
      - "0:29092"
  kafka-ui:
    ports:
      - "0:8080"
  zookeeper:
    ports: []
  mock-server:
    ports:
      - "0:1080"
  selenium-hub:
    ports:
      - "0:4444"
  centrifugo:
    ports: []
  reportportal-gateway:
    ports:
      - "0:8080"
      - "0:8081"

networks:
  default:
