services:
  nginx:
    ports:
      - "0:80"
  kafka:
    ports: []
  zookeeper:
    ports: []
  mock-server:
    ports:
      - "0:1080"
  selenium-hub:
    ports:
      - "0:4444"
  centrifugo:
    ports: []
  mongodb:
    ports:
      - "0:27017"

networks:
  default:
