ext {
    artifactId = "yaml"
}

dependencies {
    implementation platform("com.fasterxml.jackson:jackson-bom:${fasterxml_jackson}")
    implementation project(":common-utils:file")
    implementation project(":common-utils:json")
    implementation project(":testng-extensions")
    api "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml"
}