services:
  dind:
    image: docker:29.5-dind@sha256:7278248384185bcbb54c7a76b2f0a7d354c4aac920605cc1ab48968d961052fb
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --host=tcp://0.0.0.0:2375
      - --host=unix:///var/run/docker.sock
    volumes:
      - dind-data:/var/lib/docker

  runner:
    image: myoung34/github-runner:2.335.1@sha256:71231f16be5226f91c40d970c49d7e11588aba345eee6ea95ab9dc8e47d0a3d9
    depends_on:
      - dind
    environment:
      REPO_URL: ${REPO_URL}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      LABELS: ${RUNNER_LABELS}
      RUNNER_EPHEMERAL: "true"
      DISABLE_AUTO_UPDATE: "true"
      DOCKER_HOST: tcp://dind:2375
      DOCKER_TLS_CERTDIR: ""
      RUNNER_TOOL_CACHE: /opt/hostedtoolcache
    volumes:
      - runner-toolcache:/opt/hostedtoolcache
      - runner-gradle-cache:/home/runner/.gradle

volumes:
  dind-data:
  runner-toolcache:
  runner-gradle-cache:
