_commit: v2.9.1
_src_path: https://github.com/quokkify/project-toolkit.git
components: []
docker: false
project_name: Autokit
release_please: false
renovate: true
renovate_config_repository: quokkify/renovate-presets
renovate_presets:
- default
- github-actions
- java
toolkit_version: v2.9.0
