rootProject.name = 'quokkify'
include ':api'
include ':sql-utils'
include ':testng-extensions'

include ':common-utils'
include ':common-utils:core'
include ':common-utils:introspection'
include ':common-utils:awaitility'
include ':common-utils:file'
include ':common-utils:csv'
include ':common-utils:xml'
include ':common-utils:json'
include ':common-utils:html'
include ':common-utils:yaml'
include ':common-utils:http'
include ':common-utils:jwt'
include ':common-utils:google-auth'
include ':common-utils:aspects'
include ':common-utils:config'
include ':common-utils:signature'
include ':common-utils:console'
