description = "TestRail core integration"

ext {
    artifactId = "testrail-core"
}

dependencies {
    implementation project(":common-utils:http")
    implementation project(":common-utils:config")
    implementation project(":common-utils:core")
    implementation project(":common-utils:jackson:json")
}
