name: Setup Java and Gradle

description: Setup Java 21 and Gradle with cache strategy based on runner type.

inputs:
  is_self_hosted:
    description: Whether selected runner is self-hosted.
    required: true

author: quokkify

runs:
  using: composite
  steps:
    - name: 🔨Set up JDK (self-hosted, no actions cache)
      if: ${{ inputs.is_self_hosted == 'true' }}
      uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
      with:
        distribution: temurin
        java-version: "21"

    - name: 🔨Set up JDK (github-hosted, cache gradle)
      if: ${{ inputs.is_self_hosted != 'true' }}
      uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
      with:
        distribution: temurin
        cache: gradle
        java-version: "21"

    - name: 🔨Build with Gradle
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6
