[node]
detect-drivers = false
max-sessions = "5"
selenium-manager = true

[docker]
configs = ["selenium/standalone-chromium:144.0", "{\"browserName\":\"chrome\",\"hostConfig\":{\"extraHosts\":[\"host.docker.internal:host-gateway\"]}}"]
host-config-keys = ["Dns", "DnsOptions", "DnsSearch", "ExtraHosts", "Binds"]
url = "http://docker-socket-proxy:2375"
