FROM nginx:1.31.2@sha256:ec4ed8b5299e5e90694af7750eb6dffd2627317d30544d056b0371f8082f7bce

COPY conf.d/ /etc/nginx/conf.d/
COPY html/ /usr/share/nginx/html/

RUN test -f /etc/nginx/conf.d/10_site.conf
