FROM nginx:1.30.0@sha256:55d1fb0944aafb8534b253e486c6cf57d3e0c785c4f6a7b3e9f02c5a080fb2ce

COPY conf.d/ /etc/nginx/conf.d/
COPY html/ /usr/share/nginx/html/

RUN test -f /etc/nginx/conf.d/10_site.conf
