services:
  # general services

  nginx:
    image: nginx:1.29.2@sha256:3b7732505933ca591ce4a6d860cb713ad96a3176b82f7979a8dfa9973486a0d6
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/config/download_map.conf:/etc/nginx/conf.d/download_map.conf
      - ./nginx/html:/etc/nginx/html
    ports:
      - "80:80"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1@sha256:2d4bbf9cc83d9854d36582987da5f939fb9255fb128d18e3cf2c6ad825a32751
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_CREATE_TOPICS: >
        messages:1:1
    ports:
      - "29092:29092"
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.9@sha256:28dd24b6ab2a649146ec413bf64ac69af4677b743c4ed4e2c1a37addab768727
    ports:
      - "2181:2181"

  mock-server:
    image: mockserver/mockserver:5.15.0@sha256:0f9ef78c94894ac3e70135d156193b25e23872575d58e2228344964273b4af6b
    command: -logLevel DEBUG -serverPort 1080
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: true
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/expectation.json
    volumes:
      - ./mock/expectation.json:/config/expectation.json
    ports:
      - "1080:1080"

  centrifugo:
    image: centrifugo/centrifugo:v5.4.9@sha256:90be10af3cb1c73c6b6cff8f6bcf02f8c0537d6aa1ed9f2cfe59a9e776a0c3d5
    command: centrifugo -c centrifugo_new_config.json
    volumes:
      - ./centrifugo/centrifugo_new_config.json:/centrifugo/centrifugo_new_config.json
    ports:
      - "8005:8000"
    environment:
      CENTRIFUGO_PORT: 8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  mongodb:
    image: mongo:5.0.31@sha256:54bcd8da3ea5eec561b68c605046c55c6b304387dc4c2bf5b3a5f5064fbb7495
    restart: always
    ports:
      - "27017:27017"
