name: "Test Report"
on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: 🔨Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: 📦Download artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: 🔬Report summary
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2
        with:
          name: "🔬Test report: $1 $2"
          artifact: /test-report-(.*)-(.*)/
          path: "**/build/test-results/**/TEST-*.xml"
          reporter: java-junit
